language: rust
cache: cargo
rust:
  - stable
  - beta
  - 1.34.0
jobs:
  include:
    - rust: 1.34.0
      env: TEST_MINIMAL_VERSIONS=1
script:
  - |
    if [ "${TEST_MINIMAL_VERSIONS:-0}" -ne 0 ] ; then
        rustup install nightly
        cargo +nightly update -Z minimal-versions
    fi
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
notifications:
  email: false
